### ISSUE TITLE
Add ability to package application

### ISSUE THREAD

**Issue by patrickklaeren** [NETWeasel/NETWeasel.Windows#1]
Initial thoughts to be elaborated:
- Compression (zip/gzip/nupkg?)
- Versioning/updating (handled via a file, JSON?)
- Command line? Separate exe, Squirrel-esque
- Updater to be shipped

Should we have a dependency on Nuget?

**Comment by Trinitek** [comment]
https://github.com/adamhathcock/sharpcompress looks promising. Utilizing tar/lzip instead of zip seems like a good idea.

As discussed in DMs, we'll use XML for the spec file bundled with installer and update packages since the serializer is readily available in NETFx and Core right now.  We do have some flexibility as to the format of the RELEASES file that is fetched from the update repository however.

**Comment by patrickklaeren** [comment]
Implemented in the prototype.
